package com.jfinal.api;

import com.jfinal.api.BaseVilla;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Villa extends BaseVilla<Villa> {
	public static final Villa dao = new Villa();
}
